package io.github.edmaputra.iam.adapter.rest;

import java.util.Objects;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import io.github.edmaputra.iam.adapter.rest.dto.MfaActivateRequest;
import io.github.edmaputra.iam.adapter.rest.dto.MfaDisableRequest;
import io.github.edmaputra.iam.adapter.rest.dto.MfaLoginVerifyRequest;
import io.github.edmaputra.iam.application.model.MfaSetupResponse;
import io.github.edmaputra.iam.application.model.MfaStatusResponse;
import io.github.edmaputra.iam.application.model.TokenResponse;
import io.github.edmaputra.iam.application.port.in.ManageMfaUseCase;
import io.github.edmaputra.iam.domain.model.UserId;
import io.github.edmaputra.iam.domain.security.CurrentActor;
import io.github.edmaputra.iam.domain.security.CurrentActorProvider;

/**
 * Dedicated REST controller for Multi-Factor Authentication (MFA / TOTP)
 * lifecycle endpoints
 * under {@code /api/v1/auth/mfa}.
 *
 * @author edmaputra
 * @since 0.6.0
 */
@RestController
@RequestMapping("/api/v1/auth/mfa")
public class MfaController {

	private final ManageMfaUseCase manageMfaUseCase;
	private final CurrentActorProvider currentActorProvider;

	public MfaController(
			ManageMfaUseCase manageMfaUseCase,
			CurrentActorProvider currentActorProvider) {
		this.manageMfaUseCase = Objects.requireNonNull(manageMfaUseCase, "ManageMfaUseCase must not be null.");
		this.currentActorProvider = Objects.requireNonNull(currentActorProvider,
				"CurrentActorProvider must not be null.");
	}

	/**
	 * Completes second-factor authentication for an MFA challenge and returns
	 * access and refresh tokens.
	 *
	 * @param request     the MFA verification request containing the challenge
	 *                    token and code
	 * @param httpRequest the underlying HTTP servlet request for client metadata
	 * @return HTTP 200 with {@link TokenResponse}
	 */
	@PostMapping("/verify")
	public ResponseEntity<TokenResponse> verifyMfa(
			@Valid @RequestBody MfaLoginVerifyRequest request,
			HttpServletRequest httpRequest) {
		String ip = HttpRequestUtils.extractClientIp(httpRequest);
		String userAgent = HttpRequestUtils.extractUserAgent(httpRequest);
		TokenResponse response = manageMfaUseCase.verifyLogin(request.toCommand(ip, userAgent));
		return ResponseEntity.ok(response);
	}

	/**
	 * Retrieves the current user's Multi-Factor Authentication status.
	 *
	 * @return HTTP 200 with {@link MfaStatusResponse}
	 */
	@GetMapping("/status")
	public ResponseEntity<MfaStatusResponse> getMfaStatus() {
		CurrentActor actor = currentActorProvider.requireCurrentActor();
		MfaStatusResponse response = manageMfaUseCase.getStatus(new UserId(actor.userId()));
		return ResponseEntity.ok(response);
	}

	/**
	 * Initiates MFA setup by generating a new Base32 secret, OTP Auth QR URI, and
	 * backup recovery codes.
	 *
	 * @return HTTP 200 with {@link MfaSetupResponse}
	 */
	@PostMapping("/setup")
	public ResponseEntity<MfaSetupResponse> setupMfa() {
		CurrentActor actor = currentActorProvider.requireCurrentActor();
		MfaSetupResponse response = manageMfaUseCase.initiateSetup(new UserId(actor.userId()), "ed-iam");
		return ResponseEntity.ok(response);
	}

	/**
	 * Confirms and activates MFA using the first 6-digit TOTP code generated by an
	 * authenticator application.
	 *
	 * @param request the activation request containing the verification code
	 * @return HTTP 204 No Content
	 */
	@PostMapping("/activate")
	public ResponseEntity<Void> activateMfa(@Valid @RequestBody MfaActivateRequest request) {
		CurrentActor actor = currentActorProvider.requireCurrentActor();
		manageMfaUseCase.activate(new UserId(actor.userId()), request.code());
		return ResponseEntity.noContent().build();
	}

	/**
	 * Disables Multi-Factor Authentication after verifying the user's TOTP code or
	 * password.
	 *
	 * @param request the disable request containing the verification code or
	 *                password
	 * @return HTTP 204 No Content
	 */
	@PostMapping("/disable")
	public ResponseEntity<Void> disableMfa(@Valid @RequestBody MfaDisableRequest request) {
		CurrentActor actor = currentActorProvider.requireCurrentActor();
		manageMfaUseCase.disable(new UserId(actor.userId()), request.codeOrPassword());
		return ResponseEntity.noContent().build();
	}
}
